### ISSUE TITLE
Occupancy prediction results

### ISSUE THREAD

**Issue by abualhanud** [pmj110119/RenderOcc#14]
Hi, firstly, thanks for sharing your amazing work. I've run the evaluation script with the pretrained model you've provided. Even though the metrics are okay, when visualizing the results, they look kind of different when compared to the GT. Free space isn't predicted correctly, but other than that, it looks decent, the cars and the drivable road, for example, are okay. Is such behavior expected when training with 2D labels?

Prediction:

![image](https://github.com/pmj110119/RenderOcc/assets/106312980/e14bf7e6-7f99-45e4-821e-8c8ba5c6042c)

GT:

![image](https://github.com/pmj110119/RenderOcc/assets/106312980/a6fdd5be-e4a2-4881-b14f-91eb91d09001)

**Comment by pmj110119** [comment]
For visualization, you can omit voxels with a height exceeding 3m.

The reason for this issue: 
Due to the absence of 2D labels of nuScenes, we utilize the sparse 2D projections from nuScenes-lidarseg as a substitute for 2D labels for training. This resulted in a lack of supervision for the sky region throughout the training process since there is no point cloud data in the sky area, leading to the corresponding 2D labels being missing.

One solution is to create additional 2D labels for the sky region using a segmentation model (such as SegFormer),  and set the depth for the sky class to the maximum depth.

**Comment by abualhanud** [comment]
Thank you! That clears it for me
