### ISSUE TITLE
May you provide dataset pipelines, i.e. how to get the ray(gt_depth, gt_semantics, ray_o, ray_d) from the input multi-frame images.

### ISSUE THREAD

**Issue by synsin0** [pmj110119/RenderOcc#3]
Thanks for your great work. May you share an early version of dataset pipelines? Thanks, I can't wait to see RenderOcc works.

**Comment by pmj110119** [comment]
Thank you for your advice!  And I have pushed a version that includes the dataset code and an [config example](https://github.com/pmj110119/RenderOcc/blob/tmp/configs/renderocc/renderocc-7frame.py) to the **'tmp' branch**. 

Please note that this version is currently undergoing refactoring, and I'm not certain if there are some minor bugs and I haven't had a chance to write the documentation yet. 

I will also need a few days to perform validation after the Chinese National Day holiday. I apologize for any inconvenience.

**Comment by pmj110119** [comment]
> Thanks for your great work. May you share an early version of dataset pipelines? Thanks, I can't wait to see RenderOcc works.

And you can refer to the code here to generate rays from multiple frames: 
https://github.com/pmj110119/RenderOcc/blob/bd8bb8572fa1a2480f44f98183708a5b6d84664e/mmdet3d/datasets/nuscenes_dataset_occ.py#L162

**Comment by synsin0** [comment]
Thanks again! After a little effort I started training the given config, which is 2 days for 12 epochs on 8xA6000. The data_time is around 0.2-0.3. The training process cost longer than original bevstereo-occ.

**Comment by pmj110119** [comment]
I've released an update that reduces training time to just 25% of the original. Please give the updated version a try ～

**Comment by synsin0** [comment]
I replaced all modules with the new version, but the training time is almost the same with the original at the beginning( may be faster in later epochs?). May you take a look at my training log to see where's going wrong? 
[20231005_224106.log](https://github.com/pmj110119/RenderOcc/files/12820076/20231005_224106.log)

**Comment by pmj110119** [comment]
> I replaced all modules with the new version, but the training time is almost the same with the original at the beginning( may be faster in later epochs?). May you take a look at my training log to see where's going wrong? [20231005_224106.log](https://github.com/pmj110119/RenderOcc/files/12820076/20231005_224106.log)


RenderOcc takes longer time per iter compared to bevstereo-occ due to the additional rendering. It's about 40% slower (on my A100 machine, one iter of RenderOcc takes 3s with Batch Size set to 1, while bevstereo-occ takes 2.2s). 

On my own machine, it used to take 15s per iter, which might have been due to uneven server CPU load of my machine. It seems that you don't have this issue on your machine.

Fortunately, training RenderOcc requires significantly fewer epochs. After fixing some bugs, [example config](https://github.com/pmj110119/RenderOcc/blob/tmp/configs/renderocc/renderocc-7frame.py) can achieve **24+ mIoU** with only 6 epochs of training (verified)."
